title: <p align="center">Shubham Patil </p>
logo: /assets/img/MyPic.jpg
description: 
   <p align="center">
   <a href="./Resume.pdf">Resume</a>
   <a href="https://www.linkedin.com/in/shubham-patil-a060391b7/</a> |
   <a href="https://github.com/planshubham/</a>
